### ISSUE TITLE
barcode2cluster information

### ISSUE THREAD

**Issue by liuyifang** [MyersGroup/testisAtlas#1]
Hi,

Thanks for this very useful resource. I am finding barcode2cluster information for your dataset. In your elife paper supplementary file 2, it contains 32 clusters. Could you please guide me on how can I find the data about which barcode belongs to which cluster? Thanks!

> Supplementary file 2
> Summary of all differentially expressed genes in total joint wild-type and mutant cell clusters.

The format I want is something like this:

barcode | cluster
-- | --
AAAAAATCTTAN.mj_3 | 1
AAAAAATCTTGA.mj_3 | 1
AAAAACCTGGCN.Cul4a_2017-03-28 | 1
AAAAACGCGTAT.Hormad1_1_A | 2
AAAAACGTACAA.Cul4a_2017-03-30 | 3
AAAAACTAGCAG.Hormad1_1_A | 6
AAAAACTGATGG.Hormad1_2_A | 32
AAAAACTTTCGG.Hormad1_1_A | 2
AAAAAGCCATGA.CNP_2016-12-15 | 10

**Comment by daniel-wells** [comment]
Hi Yifang,

Sorry just noticed this message! I think only the soft clustering based cell scores are available to download online but if you contact Don Conrad he should be able to provide you with the final cell to cluster mapping for the hard clustering analysis.

**Comment by liuyifang** [comment]
Hi Daniel,

Thanks for your advice. I just sent an email to Dr. Don Conrad.
